name: Build and test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        env:
          AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./reports/mochawesome.html
